# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/graviton/Downloads/geant4-neutron-capture

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/graviton/Downloads/geant4-neutron-capture

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/graviton/Downloads/geant4-neutron-capture/CMakeFiles /home/graviton/Downloads/geant4-neutron-capture//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/graviton/Downloads/geant4-neutron-capture/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named neu

# Build rule for target.
neu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neu
.PHONY : neu

# fast build rule for target.
neu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/build
.PHONY : neu/fast

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/main.cc.s
.PHONY : main.cc.s

src/DetectorMessenger.o: src/DetectorMessenger.cc.o
.PHONY : src/DetectorMessenger.o

# target to build an object file
src/DetectorMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/DetectorMessenger.cc.o
.PHONY : src/DetectorMessenger.cc.o

src/DetectorMessenger.i: src/DetectorMessenger.cc.i
.PHONY : src/DetectorMessenger.i

# target to preprocess a source file
src/DetectorMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/DetectorMessenger.cc.i
.PHONY : src/DetectorMessenger.cc.i

src/DetectorMessenger.s: src/DetectorMessenger.cc.s
.PHONY : src/DetectorMessenger.s

# target to generate assembly for a file
src/DetectorMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/DetectorMessenger.cc.s
.PHONY : src/DetectorMessenger.cc.s

src/HistoManager.o: src/HistoManager.cc.o
.PHONY : src/HistoManager.o

# target to build an object file
src/HistoManager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/HistoManager.cc.o
.PHONY : src/HistoManager.cc.o

src/HistoManager.i: src/HistoManager.cc.i
.PHONY : src/HistoManager.i

# target to preprocess a source file
src/HistoManager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/HistoManager.cc.i
.PHONY : src/HistoManager.cc.i

src/HistoManager.s: src/HistoManager.cc.s
.PHONY : src/HistoManager.s

# target to generate assembly for a file
src/HistoManager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/HistoManager.cc.s
.PHONY : src/HistoManager.cc.s

src/NeuActionInitialization.o: src/NeuActionInitialization.cc.o
.PHONY : src/NeuActionInitialization.o

# target to build an object file
src/NeuActionInitialization.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuActionInitialization.cc.o
.PHONY : src/NeuActionInitialization.cc.o

src/NeuActionInitialization.i: src/NeuActionInitialization.cc.i
.PHONY : src/NeuActionInitialization.i

# target to preprocess a source file
src/NeuActionInitialization.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuActionInitialization.cc.i
.PHONY : src/NeuActionInitialization.cc.i

src/NeuActionInitialization.s: src/NeuActionInitialization.cc.s
.PHONY : src/NeuActionInitialization.s

# target to generate assembly for a file
src/NeuActionInitialization.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuActionInitialization.cc.s
.PHONY : src/NeuActionInitialization.cc.s

src/NeuDetectorConstruction.o: src/NeuDetectorConstruction.cc.o
.PHONY : src/NeuDetectorConstruction.o

# target to build an object file
src/NeuDetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuDetectorConstruction.cc.o
.PHONY : src/NeuDetectorConstruction.cc.o

src/NeuDetectorConstruction.i: src/NeuDetectorConstruction.cc.i
.PHONY : src/NeuDetectorConstruction.i

# target to preprocess a source file
src/NeuDetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuDetectorConstruction.cc.i
.PHONY : src/NeuDetectorConstruction.cc.i

src/NeuDetectorConstruction.s: src/NeuDetectorConstruction.cc.s
.PHONY : src/NeuDetectorConstruction.s

# target to generate assembly for a file
src/NeuDetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuDetectorConstruction.cc.s
.PHONY : src/NeuDetectorConstruction.cc.s

src/NeuEventAction.o: src/NeuEventAction.cc.o
.PHONY : src/NeuEventAction.o

# target to build an object file
src/NeuEventAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuEventAction.cc.o
.PHONY : src/NeuEventAction.cc.o

src/NeuEventAction.i: src/NeuEventAction.cc.i
.PHONY : src/NeuEventAction.i

# target to preprocess a source file
src/NeuEventAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuEventAction.cc.i
.PHONY : src/NeuEventAction.cc.i

src/NeuEventAction.s: src/NeuEventAction.cc.s
.PHONY : src/NeuEventAction.s

# target to generate assembly for a file
src/NeuEventAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuEventAction.cc.s
.PHONY : src/NeuEventAction.cc.s

src/NeuPhysicsList.o: src/NeuPhysicsList.cc.o
.PHONY : src/NeuPhysicsList.o

# target to build an object file
src/NeuPhysicsList.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuPhysicsList.cc.o
.PHONY : src/NeuPhysicsList.cc.o

src/NeuPhysicsList.i: src/NeuPhysicsList.cc.i
.PHONY : src/NeuPhysicsList.i

# target to preprocess a source file
src/NeuPhysicsList.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuPhysicsList.cc.i
.PHONY : src/NeuPhysicsList.cc.i

src/NeuPhysicsList.s: src/NeuPhysicsList.cc.s
.PHONY : src/NeuPhysicsList.s

# target to generate assembly for a file
src/NeuPhysicsList.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuPhysicsList.cc.s
.PHONY : src/NeuPhysicsList.cc.s

src/NeuSteppingAction.o: src/NeuSteppingAction.cc.o
.PHONY : src/NeuSteppingAction.o

# target to build an object file
src/NeuSteppingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuSteppingAction.cc.o
.PHONY : src/NeuSteppingAction.cc.o

src/NeuSteppingAction.i: src/NeuSteppingAction.cc.i
.PHONY : src/NeuSteppingAction.i

# target to preprocess a source file
src/NeuSteppingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuSteppingAction.cc.i
.PHONY : src/NeuSteppingAction.cc.i

src/NeuSteppingAction.s: src/NeuSteppingAction.cc.s
.PHONY : src/NeuSteppingAction.s

# target to generate assembly for a file
src/NeuSteppingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuSteppingAction.cc.s
.PHONY : src/NeuSteppingAction.cc.s

src/NeuTrackingAction.o: src/NeuTrackingAction.cc.o
.PHONY : src/NeuTrackingAction.o

# target to build an object file
src/NeuTrackingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuTrackingAction.cc.o
.PHONY : src/NeuTrackingAction.cc.o

src/NeuTrackingAction.i: src/NeuTrackingAction.cc.i
.PHONY : src/NeuTrackingAction.i

# target to preprocess a source file
src/NeuTrackingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuTrackingAction.cc.i
.PHONY : src/NeuTrackingAction.cc.i

src/NeuTrackingAction.s: src/NeuTrackingAction.cc.s
.PHONY : src/NeuTrackingAction.s

# target to generate assembly for a file
src/NeuTrackingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/NeuTrackingAction.cc.s
.PHONY : src/NeuTrackingAction.cc.s

src/PrimaryGeneratorAction.o: src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.o

# target to build an object file
src/PrimaryGeneratorAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.cc.o

src/PrimaryGeneratorAction.i: src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.i

# target to preprocess a source file
src/PrimaryGeneratorAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.cc.i

src/PrimaryGeneratorAction.s: src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.s

# target to generate assembly for a file
src/PrimaryGeneratorAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.cc.s

src/Run.o: src/Run.cc.o
.PHONY : src/Run.o

# target to build an object file
src/Run.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/Run.cc.o
.PHONY : src/Run.cc.o

src/Run.i: src/Run.cc.i
.PHONY : src/Run.i

# target to preprocess a source file
src/Run.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/Run.cc.i
.PHONY : src/Run.cc.i

src/Run.s: src/Run.cc.s
.PHONY : src/Run.s

# target to generate assembly for a file
src/Run.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/Run.cc.s
.PHONY : src/Run.cc.s

src/RunAction.o: src/RunAction.cc.o
.PHONY : src/RunAction.o

# target to build an object file
src/RunAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/RunAction.cc.o
.PHONY : src/RunAction.cc.o

src/RunAction.i: src/RunAction.cc.i
.PHONY : src/RunAction.i

# target to preprocess a source file
src/RunAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/RunAction.cc.i
.PHONY : src/RunAction.cc.i

src/RunAction.s: src/RunAction.cc.s
.PHONY : src/RunAction.s

# target to generate assembly for a file
src/RunAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neu.dir/build.make CMakeFiles/neu.dir/src/RunAction.cc.s
.PHONY : src/RunAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... neu"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/DetectorMessenger.o"
	@echo "... src/DetectorMessenger.i"
	@echo "... src/DetectorMessenger.s"
	@echo "... src/HistoManager.o"
	@echo "... src/HistoManager.i"
	@echo "... src/HistoManager.s"
	@echo "... src/NeuActionInitialization.o"
	@echo "... src/NeuActionInitialization.i"
	@echo "... src/NeuActionInitialization.s"
	@echo "... src/NeuDetectorConstruction.o"
	@echo "... src/NeuDetectorConstruction.i"
	@echo "... src/NeuDetectorConstruction.s"
	@echo "... src/NeuEventAction.o"
	@echo "... src/NeuEventAction.i"
	@echo "... src/NeuEventAction.s"
	@echo "... src/NeuPhysicsList.o"
	@echo "... src/NeuPhysicsList.i"
	@echo "... src/NeuPhysicsList.s"
	@echo "... src/NeuSteppingAction.o"
	@echo "... src/NeuSteppingAction.i"
	@echo "... src/NeuSteppingAction.s"
	@echo "... src/NeuTrackingAction.o"
	@echo "... src/NeuTrackingAction.i"
	@echo "... src/NeuTrackingAction.s"
	@echo "... src/PrimaryGeneratorAction.o"
	@echo "... src/PrimaryGeneratorAction.i"
	@echo "... src/PrimaryGeneratorAction.s"
	@echo "... src/Run.o"
	@echo "... src/Run.i"
	@echo "... src/Run.s"
	@echo "... src/RunAction.o"
	@echo "... src/RunAction.i"
	@echo "... src/RunAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

