#
# run_water.mac -- PURE WATER reference for the Gd comparison (2.5 MeV)
#
/control/verbose 2
/run/verbose 2
#
/testhadr/det/setMat Water_ts
/testhadr/det/setRadius 30 cm
#
/run/initialize
#
/analysis/setFileName water_ref
/analysis/h1/set 10 200 0. 20. MeV
/analysis/h1/set  2 100 0. 30. cm
/analysis/h1/set 24 150 0. 300. cm
/analysis/h1/set 25 200 0. 1000. microsecond
/analysis/h1/set 26 100 0. 30. cm
#
/gun/particle neutron
/gun/energy 2.5 MeV
#
/run/printProgress 10000
/run/beamOn 100000
